name: release-cluster-api

permissions:
  contents: read
  packages: write
  deployments: write

on:
  push:
    tags:
      - "cluster-api/v*"

jobs:
  build-and-publish-amd64:
    environment: production
    runs-on: ubuntu-24.04
    steps:
      - name: Get tag name
        uses: olegtarasov/get-tag@v2.1.4
        id: tagName
        with:
          tagRegex: "cluster-api/v(.*)"
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: build/package/Dockerfile.cluster-api
          push: true
          tags: |
            kubetail/kubetail-cluster-api:${{ steps.tagName.outputs.tag }}-amd64
            ghcr.io/${{ github.repository_owner }}/kubetail-cluster-api:${{ steps.tagName.outputs.tag }}-amd64

  build-and-publish-arm64:
    environment: production
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Get tag name
        uses: olegtarasov/get-tag@v2.1.4
        id: tagName
        with:
          tagRegex: "cluster-api/v(.*)"
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: build/package/Dockerfile.cluster-api
          push: true
          tags: |
            kubetail/kubetail-cluster-api:${{ steps.tagName.outputs.tag }}-arm64
            ghcr.io/${{ github.repository_owner }}/kubetail-cluster-api:${{ steps.tagName.outputs.tag }}-arm64

  create-and-publish-manifest:
    environment: production
    runs-on: ubuntu-24.04
    needs: [build-and-publish-amd64, build-and-publish-arm64]
    steps:
      - name: Get tag name
        uses: olegtarasov/get-tag@v2.1.4
        id: tagName
        with:
          tagRegex: "cluster-api/v(.*)"
      - name: "Setup jq"
        uses: dcarbone/install-jq-action@v3.2.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Create and push manifests
        run: |
          docker buildx imagetools create -t kubetail/kubetail-cluster-api:${{ steps.tagName.outputs.tag }} \
            kubetail/kubetail-cluster-api:${{ steps.tagName.outputs.tag }}-amd64 \
            kubetail/kubetail-cluster-api:${{ steps.tagName.outputs.tag }}-arm64
          docker buildx imagetools create -t ghcr.io/${{ github.repository_owner }}/kubetail-cluster-api:${{ steps.tagName.outputs.tag }} \
            ghcr.io/${{ github.repository_owner }}/kubetail-cluster-api:${{ steps.tagName.outputs.tag }}-amd64 \
            ghcr.io/${{ github.repository_owner }}/kubetail-cluster-api:${{ steps.tagName.outputs.tag }}-arm64
      - name: Fetch docker token
        run: |
          TOKEN=$(curl -X POST "https://hub.docker.com/v2/users/login" -H "Content-Type: application/json" -d '{"username": "${{ vars.DOCKERHUB_USERNAME }}", "password": "${{ secrets.DOCKERHUB_TOKEN }}"}' | jq -r '.token')
          echo "TOKEN=$TOKEN" >> $GITHUB_ENV
      - name: Delete extra arch manifests
        run: |
          declare -a archs=("amd64" "arm64")
          for arch in "${archs[@]}"
          do
            RESPONSE=$(curl -s -w "%{http_code}" \
              -X DELETE \
              -H "Authorization: Bearer $TOKEN" \
              "https://hub.docker.com/v2/repositories/kubetail/kubetail-cluster-api/tags/${{ steps.tagName.outputs.tag }}-$arch")
            if [ "$RESPONSE" -ne 204 ]; then
              echo "DELETE for $arch failed with status $RESPONSE"
              exit 1
            fi
          done
